a=input('digite algo')
print('O tipo primitivo desse valor é ', type(a))
print('É um número?',a.isnumeric())
print('É alfabético?',a.isalpha())
print('É alfánumérico?',a.isalnum())
print('Está em maiúsculo?',a.isupper())
print('Está em minúsculas?',a.islower())
print('Só tem espaços?',a.isspace())
print('Está capitalizada?',a.istitle())